ci: add check to make sure wasm-bindgen-cli is installed and version matches wasm-bindgen

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -78,6 +78,34 @@ jobs:
           components: rustfmt,clippy
       - run: make clippy
 
+  check_wasm_bindgen:
+    name: Pin same version of wasm-bindgen and wasm-bindgen-cli
+    runs-on: ubuntu-latest
+    steps:
+      # actions/checkout@4.1.1
+      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
+        with:
+          persist-credentials: false
+      - name: Compare Makefile wasm-bindgen-cli and Cargo.toml wasm-bindgen versions
+        run: |
+          set -euo pipefail
+
+          CARGO_VERSION=$(grep -E '^wasm-bindgen\s*=' securedrop-protocol/Cargo.toml \
+            | sed -E 's/.*"=?([^"]+)".*/\1/')
+
+          MAKEFILE_VERSION=$(grep -E '^WASM_BINDGEN_CLI_VERSION\s*:=' securedrop-protocol/Makefile \
+            | awk '{print $3}')
+
+          echo "wasm-bindgen crate version: $CARGO_VERSION"
+          echo "wasm-bindgen CLI version:   $MAKEFILE_VERSION"
+
+          if [ "$CARGO_VERSION" != "$MAKEFILE_VERSION" ]; then
+            echo "Error: wasm-bindgen version mismatch."
+            echo "Cargo.toml uses wasm-bindgen = \"$CARGO_VERSION\""
+            echo "Makefile uses WASM_BINDGEN_CLI_VERSION := $MAKEFILE_VERSION"
+            exit 1
+          fi
+
   build_wasm:
     name: wasm build
     runs-on: ubuntu-latest
@@ -111,13 +139,15 @@ jobs:
             securedrop-protocol/pkg
           key: wasm-target-${{ runner.os }}-${{ github.run_id }}
       - name: Compile for wasm32-unknown-unknown with wasm-bindgen
-        run: make build
+        run: |
+          make rust-target
+          make build
         working-directory: securedrop-protocol
 
   native_bench:
     name: Run minimal benchmarks using cargo
     runs-on: ubuntu-latest
-    needs: build_wasm
+    needs: [build_wasm, check_wasm_bindgen]
     steps:
       - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
         with:
@@ -136,6 +166,7 @@ jobs:
             securedrop-protocol/target
             securedrop-protocol/pkg
           key: wasm-target-${{ runner.os }}-${{ github.run_id }}
+      - name: Install wasm-bindgen cli
+        run: make rust-target
       - name: Run minimal cli bench
-        run: |
-          cargo bench --bench manual -- all -n 10 -k 10 -j 10
+        run: cargo bench --bench manual -- all -n 10 -k 10 -j 10
